version: '3'
networks:
  yamaguchi:
    driver: bridge
services:
  site:
    image: nginx:stable-alpine
    container_name: site
    ports:
      - "8080:80"
    volumes:
      - .:/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - yamaguchi
  mysql:
    platform: linux/x86_64
    image: mysql:8.0-debian
    container_name: dataBase
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./docker/datas/mysql/my-datavolume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - yamaguchi
  app:
    build:
      context: docker/php
    container_name: app
    volumes:
      - .:/www
      - ./docker/php/supervisor:/etc/supervisor/custom.d/
      - ./docker/php/config/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-xdebug.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    networks:
      - yamaguchi
